package com.wilddesign.clusters;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;
import org.springframework.web.bind.annotation.RequestBody;

@Controller // This means that this class is a Controller
@RequestMapping(method = RequestMethod.POST, headers ={"Accept=application/json"}, path = "/dataset") // This means URL's start with /demo (after Application path)
public class MainController {
  @Autowired // This means to get the bean called userRepository
         // Which is auto-generated by Spring, we will use it to handle the data
  private ChemicalBondRepository chemicalBondRepository;

  @PostMapping(path="/add") // Map ONLY POST Requests
  public @ResponseBody String addNewChemicalBond (@RequestBody Iterable<ChemicalBond> data) {
    // @ResponseBody means the returned String is the response, not a view name
    // @RequestParam means it is a parameter from the GET or POST request

    //User n = new User(user);
  //  n.setName(user.name);
  //  n.setEmail(user.email);
    chemicalBondRepository.saveAll(data);
    return "Saved";
  }

/*  @GetMapping(path="/all")
  public @ResponseBody Iterable<User> getAllUsers() {
    // This returns a JSON or XML with the users
    return userRepository.findAll();
  }*/
}
